#!/bin/sh

#PBS -l nodes=1:ppn=1:gpus=1
#PBS -l walltime=167:00:00
#PBS -l mem=16GB
#PBS -N open_subs_attention
#PBS -m abe
#PBS -M mvp291@nyu.edu
#PBS -j oe

cd $HOME/nmt/nmt/

module purge
module load cuda/7.5.18
module load python/intel/2.7.6
module load theano/0.8.2

THEANO_FLAGS=device=gpu,floatX=float32 python2.7 $PBS_O_WORKDIR/launchers/encDecAtt_exp.py --saveModelTo=./ckt_opensubs/att007_300k --datasetSize=300000 --reload=./ckt_opensubs/att006_300k_turn_1
